{% set name = "libnegf" %}
{% set version = "1.1.3" %}
{% set build = 0 %}
{% set mpi = mpi or "nompi" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 8d2a41791e459a203db4e4f3a9395804434ce2cd91b1bbb09111cffb032f237e

{% if mpi == "nompi" %}
{% set build = build + 100 %}
{% endif %}
build:
  number: {{ build }}
  skip: true  # [win]

  {% if mpi != "nompi" %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  string: {{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}

  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}
  {% if mpi != "nompi" %}
    - {{ name }} * {{ mpi_prefix }}_*
  {% endif %}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - cmake
    - ninja
    - fypp
    - {{ mpi }}  # [mpi == "openmpi" and build_platform != target_platform]
  host:
    - {{ mpi }}  # [mpi != "nompi"]
    - mpifx * mpi_{{ mpi }}_*  # [mpi != 'nompi']
    - libblas
    - liblapack
  run:
    - {{ mpi }}  # [mpi != "nompi"]
    - {{ pin_compatible('mpifx') }} mpi_{{ mpi }}_*  # [mpi != 'nompi']

test:
  commands:
    - test -f $PREFIX/lib/libnegf${SHLIB_EXT}

about:
  home: https://github.com/libnegf/libnegf
  license: LGPL-3.0-or-later
  license_file:
    - LICENSE
  summary: A general library for Non Equilibrium Green's Functions

extra:
  recipe-maintainers:
    - awvwgk
